version: 1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/deuscaeli/social-go
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t murakumo/around-go .
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker push murakumo/around-go
